using Microsoft.AspNetCore.Mvc;
using Progress.Sitefinity.AspNetCore.RestSdk;
using Progress.Sitefinity.AspNetCore.ViewComponents;
using Progress.Sitefinity.AspNetCore.ViewComponents.AttributeConfigurator.Attributes;
using Progress.Sitefinity.AspNetCore.Widgets.ViewComponents.Common;
using Progress.Sitefinity.Renderer.Designers.Attributes;
using Progress.Sitefinity.Renderer.Entities.Content;
using Progress.Sitefinity.RestSdk;
using Progress.Sitefinity.RestSdk.Client;
using Progress.Sitefinity.RestSdk.Dto;
using System;
using System.ComponentModel.DataAnnotations;
using System.Threading.Tasks;
using WebApp.ViewModels;

namespace ViewComponents.CustomImage
{
    /// <summary>
    /// Test widget with different kind of restrictions for its properties. For more information on creating widgets
    /// visit <see href="https://www.progress.com/documentation/sitefinity-cms/asp.net-core-widget-components">this page.</see>
    /// </summary>
    [SitefinityWidget]
    public class CustomImageViewComponent : ViewComponent
    {
        /// <summary>
        /// Invokes the view.
        /// </summary>
        /// <param name="context"></param>
        /// <returns></returns>

        public CustomImageViewComponent(IRestClient _restClient, IStyleClassesProvider _styleClassesProvider)
        {
            this.restClient = _restClient;
            this.styleClassesProvider = _styleClassesProvider;
        }
        IStyleClassesProvider styleClassesProvider;
        IRestClient restClient;
        public async Task<IViewComponentResult> InvokeAsync(IViewComponentContext<CustomImageEntity> context)
        {
            if (context == null)
            {
                throw new ArgumentNullException(nameof(context));
            }
            CustomImageViewModel model = new CustomImageViewModel();
            model.ViewName = context.Entity.ViewName;
            await GetImageAsync(context, model);
            return this.View(model.ViewName,model);
        }
        private async Task GetImageAsync(IViewComponentContext<CustomImageEntity> context, CustomImageViewModel model)
        {
            var imageContext = context.Entity?.Image;

            if (imageContext == null || !imageContext.HasSelectedItems())
            {
                return;
            }

            //var imageResult = await restClient.GetItems<ImageDto>(imageContext);
            var imageResult = await restClient.GetItems<ImageDto>(imageContext);

            if (imageResult?.Items != null && imageResult?.Items?.Count > 0)
            {
                model.Image = imageResult.Items[0];
            }
        }
    }

    /// <summary>
    /// The test model for the load tests widget. For a list of supported properties
    /// visit <see href="https://www.progress.com/documentation/sitefinity-cms/autogenerated-field-types">this page.</see>
    /// </summary>
    public class CustomImageEntity
    {
        /// <summary>
        /// Gets or sets a value indicating whether a boolean property is true or false.
        /// </summary>
        [Content(Type = KnownContentTypes.Images, AllowMultipleItemsSelection = false)]
        [Required]
        public MixedContentContext Image { get; set; }

        [ViewSelector]
        public string ViewName { get; set; }
    }
}
