using AngleSharp.Css.Dom;
using Microsoft.AspNetCore.Mvc;
using Progress.Sitefinity.AspNetCore.ViewComponents;
using Progress.Sitefinity.AspNetCore.ViewComponents.AttributeConfigurator.Attributes;
using Progress.Sitefinity.AspNetCore.Widgets.Models.Common;
using Progress.Sitefinity.AspNetCore.Widgets.ViewComponents.Common;
using Progress.Sitefinity.Renderer.Designers.Attributes;
using Progress.Sitefinity.Renderer.Models;
using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using System.Runtime.Serialization;
using ViewComponents.Card;
using WebApp.ViewModels.Card;
using WebApp.ViewModels.CustomList;

namespace ViewComponents.CustomList
{
    /// <summary>
    /// Test widget with different kind of restrictions for its properties. For more information on creating widgets
    /// visit <see href="https://www.progress.com/documentation/sitefinity-cms/asp.net-core-widget-components">this page.</see>
    /// </summary>
    [SitefinityWidget]
    public class CustomListViewComponent : ViewComponent
    {
        private IStyleClassesProvider styles;
        public CustomListViewComponent(IStyleClassesProvider styleClassesProvider)
        {
            styles = styleClassesProvider;
        }
        /// <summary>
        /// Invokes the view.
        /// </summary>
        /// <param name="context"></param>
        /// <returns></returns>
        public IViewComponentResult Invoke(IViewComponentContext<CustomListEntity> context)
        {
            if (context == null)
            {
                throw new ArgumentNullException(nameof(context));
            }

            CustomListViewModel model = new CustomListViewModel();
            BuildSectionMargins(context, model);
            model.Title = context.Entity.Title;
            model.LinkText = context.Entity.LinkText;
            model.Items = context.Entity.Items;
            model.Link = context.Entity.Link;

            return this.View(context.Entity.View, model);
        }
        private void BuildSectionMargins(IViewComponentContext<CustomListEntity> context, CustomListViewModel model)
        {
            switch (context.Entity.TextAlignment)
            {
                case TextAlignment.Center:
                    model.TextAlign = "center";
                    break;
                case TextAlignment.Right:
                    model.TextAlign = "end";
                    break;
                case TextAlignment.Left:
                default:
                    model.TextAlign = "start";
                    break;
            }
            var margins = this.styles.GetMarginsClasses(context.Entity.Margin);
            if (!string.IsNullOrEmpty(margins))
            {
                model.Margin = margins;
            }
        }
    }



    /// <summary>
    /// The test model for the load tests widget. For a list of supported properties
    /// visit <see href="https://www.progress.com/documentation/sitefinity-cms/autogenerated-field-types">this page.</see>
    /// </summary>
    public class CustomListEntity
    {
        /// <summary>
        /// Gets or sets a value indicating whether a boolean property is true or false.
        /// </summary>

        [Required]
        [DisplayName("Title")]
        public string Title { get; set; }

        [DisplayName("Items")]
        public IList<ListItemBase> Items { get; set; } = new List<ListItemBase>();


        [Description("Page, Content Item, or Url")]
        public LinkModel Link { get; set; }


        [DisplayName("Link Text")]
        public string LinkText { get; set; }

        public TextAlignment TextAlignment { get; set; }

        [TableView("Section")]
        public MarginStyle Margin{ get; set; }

        [ViewSelector]
        public string View { get; set; }
    }

    public class ListItemBase
    {
        public string ItemTitle { get; set; }
        public string ItemText { get; set; }
        public string ItemLinkText { get; set; }
    }

    public enum TextAlignment
    {
        Center,
        Left,
        Right
    }
}
