using System;
using Microsoft.AspNetCore.Mvc;
using Progress.Sitefinity.AspNetCore.ViewComponents;
using WebApp.ViewModels.TextCard;

namespace ViewComponents.TextCard
{
    /// <summary>
    /// Test widget with different kind of restrictions for its properties. For more information on creating widgets
    /// visit <see href="https://www.progress.com/documentation/sitefinity-cms/asp.net-core-widget-components">this page.</see>
    /// </summary>
    [SitefinityWidget]
    public class TextCardViewComponent : ViewComponent
    {
        /// <summary>
        /// Invokes the view.
        /// </summary>
        /// <param name="context"></param>
        /// <returns></returns>
        public IViewComponentResult Invoke(IViewComponentContext<TextCardEntity> context)
        {
            if (context == null)
            {
                throw new ArgumentNullException(nameof(context));
            }
            var model = new TextCardViewModel();
            model.ButtonLink = context.Entity.ButtonLink;
            model.Text = context.Entity.Text;
            model.Title = context.Entity.Title;
            model.ButtonText = context.Entity.ButtonText;

            return this.View(model);
        }
    }

    /// <summary>
    /// The test model for the load tests widget. For a list of supported properties
    /// visit <see href="https://www.progress.com/documentation/sitefinity-cms/autogenerated-field-types">this page.</see>
    /// </summary>
    public class TextCardEntity
    {
        /// <summary>
        /// Gets or sets a value indicating whether a boolean property is true or false.
        /// </summary>
        public string Title { get; set; }
        public string Text { get; set; }
        public string ButtonText { get; set; }
        public string ButtonLink { get; set; }

    }
}
