using Microsoft.AspNetCore.Mvc;
using Progress.Sitefinity.AspNetCore.RestSdk;
using Progress.Sitefinity.AspNetCore.ViewComponents;
using Progress.Sitefinity.AspNetCore.ViewComponents.AttributeConfigurator.Attributes;
using Progress.Sitefinity.AspNetCore.Widgets.ViewComponents.Common;
using Progress.Sitefinity.Renderer.Designers;
using Progress.Sitefinity.Renderer.Designers.Attributes;
using Progress.Sitefinity.Renderer.Entities.Content;
using Progress.Sitefinity.Renderer.Models;
using Progress.Sitefinity.RestSdk;
using Progress.Sitefinity.RestSdk.Dto;
using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using System.Threading.Tasks;
using WebApp.ViewModels.Card;

namespace ViewComponents.Card
{
    /// <summary>
    /// Test widget with different kind of restrictions for its properties. For more information on creating widgets
    /// visit <see href="https://www.progress.com/documentation/sitefinity-cms/asp.net-core-widget-components">this page.</see>
    /// </summary>
    [SitefinityWidget]
    public class CardViewComponent : ViewComponent
    {
        public CardViewComponent(IRestClient _restClient, IStyleClassesProvider _styleClassesProvider)
        {
            this.restClient = _restClient;
            this.styleClassesProvider = _styleClassesProvider;
        }
        IStyleClassesProvider styleClassesProvider;
        IRestClient restClient;
        /// <summary>
        /// Invokes the view.
        /// </summary>
        /// <param name="context"></param>
        /// <returns></returns>
        public async Task<IViewComponentResult> InvokeAsync(IViewComponentContext<CardEntity> context)
        {
            CardViewModel model = new CardViewModel();
            if (context == null)
            {
                throw new ArgumentNullException(nameof(context));
            }
            if (context?.Entity == null)
            {
                return View(new CardViewModel());
            }

            await GetImageAsync(context, model);
            model.CardText = context.Entity.CardText;
            model.CardTitle = context.Entity.CardTitle;
            model.LinkText = context.Entity.LinkText;
            model.Link = context.Entity.Link;
            model.CardSubtitle = context.Entity.CardSubtitle;
            model.ViewName = context.Entity.ViewName;
            

            return this.View(model.ViewName, model);
        }
        private async Task GetImageAsync(IViewComponentContext<CardEntity> context, CardViewModel model)
        {
            var imageContext = context.Entity?.Image;

            if (imageContext == null || !imageContext.HasSelectedItems())
            {
                return;
            }

            var imageResult = await restClient.GetItems<ImageDto>(imageContext);


            if (imageResult?.Items != null && imageResult?.Items?.Count > 0)
            {
                model.Image = imageResult.Items[0];
            }
        }
    }

    /// <summary>
    /// The test model for the load tests widget. For a list of supported properties
    /// visit <see href="https://www.progress.com/documentation/sitefinity-cms/autogenerated-field-types">this page.</see>
    /// </summary>
    public class CardEntity
    {
        /// <summary>
        /// Gets or sets a value indicating whether a boolean property is true or false.
        /// </summary>
        

        private const string CardSectionName = "Card";

        #region Card Section
        [ContentSection(CardSectionName)]
        [Content(Type = KnownContentTypes.Images, AllowMultipleItemsSelection = false)]
        [Required]
        public MixedContentContext Image { get; set; }

        [ContentSection(CardSectionName)]
        [DisplayName("Card Title")]
        
        public string CardTitle { get; set; }

        [ContentSection(CardSectionName)]
        [DisplayName("Card Subtitle")]
        
        public string CardSubtitle { get; set; }

        [ContentSection(CardSectionName)]
        [DataType(customDataType: KnownFieldTypes.TextArea)]
        [DisplayName("Card Text")]
        
        public string CardText { get; set; }
        #endregion

        #region Button Section
        [Description("Page, Content Item, or Url")]
        public LinkModel Link { get; set; }


        [DisplayName("Link Text")]
        public string LinkText { get; set; }
        #endregion

        [ViewSelector]
        public string ViewName { get; set; }
    }
}
