using System;
using Microsoft.AspNetCore.Mvc;
using Progress.Sitefinity.AspNetCore.ViewComponents;
using Progress.Sitefinity.AspNetCore.ViewComponents.AttributeConfigurator.Attributes;
using WebApp.ViewModels.CustomForm;

namespace ViewComponents.CustomForm
{
    /// <summary>
    /// Test widget with different kind of restrictions for its properties. For more information on creating widgets
    /// visit <see href="https://www.progress.com/documentation/sitefinity-cms/asp.net-core-widget-components">this page.</see>
    /// </summary>
    [SitefinityWidget]
    public class CustomFormViewComponent : ViewComponent
    {
        /// <summary>
        /// Invokes the view.
        /// </summary>
        /// <param name="context"></param>
        /// <returns></returns>
        public IViewComponentResult Invoke(IViewComponentContext<CustomFormEntity> context)
        {
            if (context == null)
            {
                throw new ArgumentNullException(nameof(context));
            }
            var model = new CustomFormViewModel();
            model.Title = context.Entity.Title;
            model.Description = context.Entity.Description;
            model.Placeholder = context.Entity.Placeholder;
            model.ButtonText = context.Entity.ButtonText;
            model.View = context.Entity.View;

            return this.View(model.View,model);
        }
    }

    /// <summary>
    /// The test model for the load tests widget. For a list of supported properties
    /// visit <see href="https://www.progress.com/documentation/sitefinity-cms/autogenerated-field-types">this page.</see>
    /// </summary>
    public class CustomFormEntity
    {
        /// <summary>
        /// Gets or sets a value indicating whether a boolean property is true or false.
        /// </summary>
        public string Title { get; set; }
        public string Description { get; set; }
        public string Placeholder { get; set; }
        public string ButtonText { get; set; }

        [ViewSelector]
        public string View { get; set; }
    }
}
