using Microsoft.AspNetCore.Mvc;
using Progress.Sitefinity.AspNetCore.ViewComponents;
using Progress.Sitefinity.AspNetCore.ViewComponents.AttributeConfigurator.Attributes;
using Progress.Sitefinity.AspNetCore.Widgets.Models.Common;
using Progress.Sitefinity.AspNetCore.Widgets.Models.Section;
using Progress.Sitefinity.AspNetCore.Widgets.ViewComponents.Common;
using Progress.Sitefinity.RestSdk;
using System;
using ViewComponents.CustomList;
using WebApp.Models.StaticSection;
using WebApp.ViewModels.CustomList;
using WebApp.ViewModels.StaticSection;

namespace ViewComponents.StaticSection
{
    /// <summary>
    /// Test widget with different kind of restrictions for its properties. For more information on creating widgets
    /// visit <see href="https://www.progress.com/documentation/sitefinity-cms/asp.net-core-widget-components">this page.</see>
    /// </summary>
    [SitefinityWidget]
    public class StaticSectionViewComponent : ViewComponent
    {
        private IStyleClassesProvider styles;
        private IRestClient service;
        public StaticSectionViewComponent(IStyleClassesProvider styleClassesProvider, IRestClient service)
        {
            styles = styleClassesProvider;
            this.service = service;
        }
        /// <summary>
        /// Invokes the view.
        /// </summary>
        /// <param name="context"></param>
        /// <returns></returns>
        public IViewComponentResult Invoke(ICompositeViewComponentContext<StaticSectionEntity> context)
        {
            if (context == null)
                throw new ArgumentNullException(nameof(context));

            foreach (var child in context.ChildComponents)
            {
                child.Properties.Add("FromParent", "Val from parent");
            }

            var viewModel = new StaticSectionViewModel()
            {
                Context = context
            };

            return this.View(context.Entity.ViewType ?? "Container", viewModel);
        }
        //private void BuildSectionMargins(IViewComponentContext<StaticSectionEntity> context, StaticSectionViewModel model)
        //{
        //    switch (context.Entity.TextAlignment)
        //    {
        //        case TextAlignment.Center:
        //            model.TextAlign = "center";
        //            break;
        //        case TextAlignment.Right:
        //            model.TextAlign = "end";
        //            break;
        //        case TextAlignment.Left:
        //        default:
        //            model.TextAlign = "start";
        //            break;
        //    }
        //    var margins = this.styles.GetMarginsClasses(context.Entity.Margin);
        //    if (!string.IsNullOrEmpty(margins))
        //    {
        //        model.Margin = margins;
        //    }
        //}
    }

    /// <summary>
    /// The test model for the load tests widget. For a list of supported properties
    /// visit <see href="https://www.progress.com/documentation/sitefinity-cms/autogenerated-field-types">this page.</see>
    /// </summary>
    public class StaticSectionEntity
    {
        [ViewSelector("StaticSection")]
        public string ViewType { get; set; }
    }
}
